import json
import argparse
from transformers import T5Tokenizer
from pprint import pprint
from tqdm.auto import tqdm
from multiprocessing import Pool

def create_parser():
	parser = argparse.ArgumentParser()
	parser.add_argument('--psa_instance',help='path to psa_instance generated by NTC2PSAdataset.py')
	parser.add_argument('--output_path',help='output path')
	return parser

def main():
	parser = create_parser()
	args = parser.parse_args()
	psa_instance_path = args.psa_instance
	output_path = args.output_path

	with open(psa_instance_path,mode='r') as f:
		lines = f.readlines()
	for line in lines:
		psa_dict = json.loads(line)
		

if __name__ == '__main__':
	main()